server:
  port: 8001

spring:
  application:
    #在进行服务注册时会使用这个名字
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities

#配置Eureka客户端，将本服务注册至Eureka Server
eureka:
  client:
    #标识是否将自己注册进Eureka Server
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为徒惹。单点无所谓，集权必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #集群的话，url之间使用逗号隔开
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/